### ISSUE TITLE
Friendly FYI - handler.py doesn't match modifications suggested in awstip article

### ISSUE THREAD

**Issue by mryoho** [oliverschenk/aws-secrets-manager-rotation#1]
Hi there,

Maybe you're already aware, but I was looking at this repo and the [awstip article](https://awstip.com/achieving-rds-password-rotation-with-secrets-manager-3444fa30c94b) and I noticed that the modifications you suggested in that article ([e.g.](https://gist.github.com/oliverschenk/dac0e62f6fc1e52c96497f84ef3f1bee/raw/8a535f4463f795b8c8c80fef2b32277786783283/handler.py)) are not present in the repo code.

Just thought I'd let you know!

**Comment by oliverschenk** [comment]
Thanks very much for the pickup - I updated the handler accordingly and tested it again. Fingers crossed!
